# Generated by Django 5.2.11 on 2026-02-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
